#!/bin/sh
# Kikaha Project Watcher
# Since: 12/Mar/2019

# VARIABLES
CWD=`pwd`
KDIR=$(cd `dirname "${0}"` && pwd)
KIKAHA_STATUS=$(ps -ef | grep kikaha | grep -v grep | grep -v kikaha-cli | wc -l)
KIKAHA=$0
SLACK_HOOK=$(awk -F 'SLACK_HOOK=' '{print $2}' .env)
SLACK_ERROR='You must provide the slack token at .env so we can send you a warning.'
ENV_ERROR='You must be in a production environment in order to use the watcher.'
cd $CWD

# INCLUDES
for include in $KDIR/base/inc.*.sh; do
	. $include
done

# CONFIGURATIONS
for conf in $KDIR/conf/*.conf; do
	debug "Reading configuration: $(grape $conf)"
	. $conf
done

if [ $KIKAHA_STATUS != 0 ]; then
  echo $(grape Status:) 'Kikaha service is currently running.'
else
  echo $(grape Status:) 'Kikaha service is not running.'
  echo 'Restarting Kikaha...'
  curl --silent -X POST -H 'Content-type: application/json' --data '{"text":"*[FAKE]* A instância do projeto `catalog` não está ativa. Executando novamente..."}' $SLACK_HOOK || echo $SLACK_ERROR
  sudo bash kikaha.sh start 2>/dev/null || echo $ENV_ERROR && exit;
fi

sleep 2

while true; do exec "./watcher"; done
